# 1. Import Libraries

In [1]:

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
#https://figshare.manchester.ac.uk/articles/dataset/Interactive_information_dashboards_user_performance_and_interaction_patterns/21335622?utm_source=chatgpt.com

df = pd.read_csv("../data/raw/dependent and independent variables.csv")
df

,P,DB,Issue,Type,Q,Answer,Time,SGLT,mental,physical,temporal,performance,effort,frustration,avg_others,avg_all
0,f118ebdd7e9350d704d9f91ee7de2702,3,Order&Grouping,Baseline,1,0,5.33,0,14.0,10.0,6,14,10,14.0,10.8,11.33
1,f118ebdd7e9350d704d9f91ee7de2702,2,InforOverload,Intervention,1,1,8.53,0,6.0,2.0,4,20,4,10.0,5.2,7.67
2,f118ebdd7e9350d704d9f91ee7de2702,1,InforOverload,Baseline,1,0,2.25,0,1.0,1.0,1,20,0,0.0,0.6,3.83
3,f118ebdd7e9350d704d9f91ee7de2702,3,Order&Grouping,Baseline,2,0,7.85,0,10.0,10.0,6,20,10,18.0,10.8,12.33
4,f118ebdd7e9350d704d9f91ee7de2702,7,DataUnderstanding,Baseline,2,1,8.82,0,4.0,4.0,2,8,5,14.0,5.8,6.17
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1003,8f1b5140f2e94d7a0b76b86a25134ca8,3,Order&Grouping,Baseline,2,0,2.63,3,0.0,0.0,0,0,2,2.0,0.8,0.67
1004,8f1b5140f2e94d7a0b76b86a25134ca8,7,DataUnderstanding,Baseline,2,1,2.15,3,4.0,2.0,2,7,1,1.0,2.0,2.83
1005,8f1b5140f2e94d7a0b76b86a25134ca8,7,DataUnderstanding,Baseline,1,0,4.93,3,6.0,4.0,4,6,8,6.0,5.6,5.67
1006,8f1b5140f2e94d7a0b76b86a25134ca8,6,DataPresentation,Intervention,2,1,3.25,3,4.0,2.0,2,7,1,1.0,2.0,2.83
1007,8f1b5140f2e94d7a0b76b86a25134ca8,5,DataPresentation,Baseline,1,0,1.60,3,2.0,2.0,2,10,1,1.0,1.6,3.00

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1008 entries, 0 to 1007
Data columns (total 16 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   P            1008 non-null   object
 1   DB           1008 non-null   int64
 2   Issue        1008 non-null   object
 3   Type         1008 non-null   object
 4   Q            1008 non-null   int64
 5   Answer       1008 non-null   int64
 6   Time         1008 non-null   float64
 7   SGLT         1008 non-null   int64
 8   mental       1008 non-null   float64
 9   physical     1008 non-null   float64
 10  temporal     1008 non-null   int64
 11  performance  1008 non-null   int64
 12  effort       1008 non-null   int64
 13  frustration  1008 non-null   float64
 14  avg_others   1008 non-null   float64
 15  avg_all      1008 non-null   float64
dtypes: float64(6), int64(7), object(3)
memory usage: 126.1+ KB

In [4]:
df.describe()

,DB,Q,Answer,Time,SGLT,mental,physical,temporal,performance,effort,frustration,avg_others,avg_all
count,1008.000000,1008.000000,1008.000000,1008.000000,1008.000000,1008.000000,1008.000000,1008.000000,1008.000000,1008.000000,1008.000000,1008.000000,1008.000000
mean,4.500000,1.500000,0.546627,3.518829,2.571429,5.531746,3.321429,3.893849,13.562500,4.962302,4.729167,4.487698,6.000139
std,2.292425,0.500248,0.498068,2.921440,1.094746,4.438813,3.762019,4.379654,6.055032,4.685392,5.457706,3.691544,3.019524
min,1.000000,1.000000,0.000000,0.400000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,2.750000,1.000000,0.000000,1.745000,2.000000,2.000000,1.000000,1.000000,10.000000,1.000000,1.000000,1.400000,3.830000
50%,4.500000,1.500000,1.000000,2.750000,3.000000,4.000000,2.000000,2.000000,15.000000,3.000000,2.000000,3.600000,5.330000
75%,6.250000,2.000000,1.000000,4.272500,3.000000,8.000000,5.000000,5.250000,18.000000,8.000000,8.000000,6.800000,7.670000
max,8.000000,2.000000,1.000000,25.530000,4.000000,20.000000,20.000000,20.000000,20.000000,20.000000,20.000000,20.000000,18.330000

In [5]:
df.isnull().sum()

P              0
DB             0
Issue          0
Type           0
Q              0
Answer         0
Time           0
SGLT           0
mental         0
physical       0
temporal       0
performance    0
effort         0
frustration    0
avg_others     0
avg_all        0
dtype: int64

In [6]:
df.duplicated().sum()

np.int64(0)

In [7]:
df.head()

,P,DB,Issue,Type,Q,Answer,Time,SGLT,mental,physical,temporal,performance,effort,frustration,avg_others,avg_all
0,f118ebdd7e9350d704d9f91ee7de2702,3,Order&Grouping,Baseline,1,0,5.33,0,14.0,10.0,6,14,10,14.0,10.8,11.33
1,f118ebdd7e9350d704d9f91ee7de2702,2,InforOverload,Intervention,1,1,8.53,0,6.0,2.0,4,20,4,10.0,5.2,7.67
2,f118ebdd7e9350d704d9f91ee7de2702,1,InforOverload,Baseline,1,0,2.25,0,1.0,1.0,1,20,0,0.0,0.6,3.83
3,f118ebdd7e9350d704d9f91ee7de2702,3,Order&Grouping,Baseline,2,0,7.85,0,10.0,10.0,6,20,10,18.0,10.8,12.33
4,f118ebdd7e9350d704d9f91ee7de2702,7,DataUnderstanding,Baseline,2,1,8.82,0,4.0,4.0,2,8,5,14.0,5.8,6.17

In [8]:
df["Issue"].value_counts()

Issue
Order&Grouping       252
InforOverload        252
DataUnderstanding    252
DataPresentation     252
Name: count, dtype: int64

In [9]:
df["Type"].value_counts()

Type
Baseline        504
Intervention    504
Name: count, dtype: int64

In [10]:
df["Answer"].value_counts()

Answer
1    551
0    457
Name: count, dtype: int64

In [11]:
df["DB"].value_counts().sort_index()

DB
1    126
2    126
3    126
4    126
5    126
6    126
7    126
8    126
Name: count, dtype: int64